### ISSUE TITLE
Meaning of "Continuing song cutoff"?

### ISSUE THREAD

**Issue by Connum** [1aienthusiast/audiocraft-infinity-webui#2]
Thanks for the work! Can you explain what the "Continuing song cutoff" setting does?

**Comment by 1aienthusiast** [comment]
the continuing song cutoff setting is the number of seconds that should be taken from the end of the continuing song, for example a song you want to continue is 30 seconds, and you set the continuing song cutoff to 10 seconds, the last 10 seconds will be used to continue the song

**Comment by Connum** [comment]
Thanks for the quick response!
