### ISSUE TITLE
a couple of bugs

### ISSUE THREAD

**Issue by davidebaltieri31** [1aienthusiast/audiocraft-infinity-webui#3]
Hi!

Installed everything on python 3.11.4.

I had to make a couple of adjustements for it to work:

in set_seed after line 51 I added:
**seed = np.uint32(seed).item()** 
to convert back to int otherwise random.seed(seed) would throw an exception

in generate in line 203
instead of **file_name = ""** changed it to **file_name = None**
otherwise gradio was crashing when trying to load generated file in the ui

**Comment by 1aienthusiast** [comment]
i recommend using python 3.9 (forgot to put in readme) but i've implemented the fixes, thanks!
