### ISSUE TITLE
AttributeError after updating to latest version

### ISSUE THREAD

**Issue by Jongulo** [1aienthusiast/audiocraft-infinity-webui#4]
Getting this error after updating to latest version

Traceback (most recent call last):
  File "C:\audiocraft-infinity-webui\webui.py", line 17, in <module>
    from modules import shared, ui
  File "C:\audiocraft-infinity-webui\modules\ui.py", line 5, in <module>
    class ToolButton(gr.Button, gr.components.FormComponent):
AttributeError: module 'gradio.components' has no attribute 'FormComponent'
NativeCommandExitException: Program "python.exe" ended with non-zero exit code: 1.

**Comment by 1aienthusiast** [comment]
what version of python are you using? what version of gradio do you have?
I'm using python 3.9 and gradio 3.34.0

**Comment by Jongulo** [comment]
I'm using python 3.9.8 and gradio 3.35.0 should I downgrade the gradio version?

**Comment by 1aienthusiast** [comment]
I doubt that's the issue but You should try I guess

**Comment by 1aienthusiast** [comment]
can confirm, gradio 3.35.0 errors out with `AttributeError: module 'gradio.components' has no attribute 'FormComponent'`

**Comment by Jongulo** [comment]
Yep that was the issue
