### ISSUE TITLE
[Feature Request] Queue Implementation for Prompts Submission

### ISSUE THREAD

**Issue by FeelTheFonk** [1aienthusiast/audiocraft-infinity-webui#7]
Hello and thank you "infinitely" for this tool :)

I am writing to suggest a new feature that could enhance user experience: the implementation of a queue system for prompts submission.

In the user interface of another project, [audiocraft-webui](https://github.com/CoffeeVampir3/audiocraft-webui), there is a feature that allows the queueing of prompts. When a user clicks on the "Submit" button multiple times, instead of overwriting the current prompt, the new prompts are added to a queue.

I believe that incorporating a similar feature into this project could significantly improve its usability, as it would allow users to submit multiple different prompts in a queue without having to wait for each to be processed before submitting the next.

Thank you again for all your work on this tool. I look forward to any discussion on this feature request!

Best regards,

Peace

**Comment by 1aienthusiast** [comment]
Thanks for the idea, I'll be adding it to the WebUI.

**Comment by 1aienthusiast** [comment]
I've implemented it in the https://github.com/1aienthusiast/audiocraft-infinity-webui/tree/main-queue branch, the reason i didnt implement it in the main branch is because the UI implementation is unfinished (you have to press the refresh button to refresh the audio list in the WebUI to see what songs finished generating), and I don't know how to make the gradio UI update from another part of the script

**Comment by FeelTheFonk** [comment]
> I've implemented it in the https://github.com/1aienthusiast/audiocraft-infinity-webui/tree/main-queue branch, the reason i didnt implement it in the main branch is because the UI implementation is unfinished (you have to press the refresh button to refresh the audio list in the WebUI to see what songs finished generating), and I don't know how to make the gradio UI update from another part of the script

Thank you!
